version: "3.9"

services:
  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: etl_pipeline
    ports:
      - "5432:5432"

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: etl_pipeline
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"